### ISSUE TITLE
插件启用后一直 404

### ISSUE THREAD

**Issue by appdev** [gogobody/OneTypecho_Plugin#2]
启用后访问地址 url/onetypecho/v1/category/index 等等。全部 404。禁用插件后在启用就报错了。。

**Comment by gogobody** [comment]
可以开下typecho 的debug，贴下报错

**Comment by appdev** [comment]
之前用的是 sqlite 再次安装报错，又重新使用 mysql 安装了一次，倒是没有报错。但是还是访问 404。后台设置里会因为没有填写小程序的 appid 这些不能访问吗？

http://nva.ff.sy/onetypecho/v1/setting/home

typecho 使用的是正式版

**Comment by gogobody** [comment]
开伪静态。

**Comment by appdev** [comment]
可以了，谢谢，用的宝塔面板，有两个 typecho 的静态规则。只有配合这个是正常的：
```
 if (!-e $request_filename) {
        rewrite ^(.*)$ /index.php$1 last;
    }
```
